#include "stm32f4xx.h"

/**
 * @brief Configures GPIO pins for the LED on the STM32 board.
 * This function sets up the necessary GPIO configurations to control
 * the LED connected to a specific pin (e.g., PC13).
 */
void GPIO_Config(void);

/**
 * @brief Configures the system clock.
 * This function sets up the system clock to use the HSI (High-Speed Internal)
 * oscillator as the clock source and configures the Flash latency.
 * 
 * @param flash_latency Flash memory latency setting (e.g., FLASH_ACR_LATENCY_0WS).
 */
void SystemClock_Config(uint8_t flash_latency);

/**
 * @brief Configures Timer 11 for periodic interrupts.
 * This function sets up Timer 11 to generate an interrupt every 500 milliseconds,
 * which can be used for periodic tasks like toggling an LED.
 */
void Timer11_Config(void);

/**
 * @brief Generic timer configuration function.
 * This function configures a given timer with a specified prescaler and period,
 * allowing for flexible timer setup for different timing requirements.
 * 
 * @param TIMx Pointer to the TIM peripheral to configure (e.g., TIM11).
 * @param prescaler Prescaler value to divide the clock frequency.
 * @param period Auto-reload value to set the timer period.
 */
void Timer_Config(TIM_TypeDef *TIMx, uint32_t prescaler, uint32_t period);

/**
 * @brief Interrupt Service Routine (ISR) for Timer 11.
 * This function handles the interrupt generated by Timer 11, typically used to
 * perform actions like toggling an LED each time the timer overflows.
 */
void TIM1_TRG_COM_TIM11_IRQHandler(void);

int main(void) {
    // Configure the system clock to use HSI with 0 wait states for Flash
    SystemClock_Config(FLASH_ACR_LATENCY_0WS);

    // Configure GPIO for LED output
    GPIO_Config();

    // Configure Timer 11 to generate an interrupt every 500 ms
    Timer11_Config();

    // Main loop (LED toggling is handled in the Timer 11 interrupt)
    while (1) {
        // Optional: Place low-power mode or other tasks here
    }
}

/**
 * @brief Configure GPIO for LED on PC13.
 */
void GPIO_Config(void) {
    // Enable GPIOC clock
    RCC->AHB1ENR |= RCC_AHB1ENR_GPIOCEN;
    
    // Configure PC13 as output
    GPIOC->MODER &= ~(GPIO_MODER_MODE13_Msk);  // Clear mode bits
    GPIOC->MODER |= (1 << GPIO_MODER_MODE13_Pos);  // Set to general purpose output
    
    // Set PC13 to low (LED off initially)
    GPIOC->ODR &= ~GPIO_ODR_OD13;
}

/**
 * @brief Configure the system clock to use HSI.
 * @param flash_latency Flash memory latency setting (e.g., FLASH_ACR_LATENCY_0WS).
 */
void SystemClock_Config(uint8_t flash_latency) {
    // Enable Power Control clock
    RCC->APB1ENR |= RCC_APB1ENR_PWREN;
    
    // Configure Flash latency
    FLASH->ACR = flash_latency;

    // Ensure PLL is off
    RCC->CR &= ~RCC_CR_PLLON;
    while (RCC->CR & RCC_CR_PLLRDY);

    // Enable HSI and wait until it is ready
    RCC->CR |= RCC_CR_HSION;
    while (!(RCC->CR & RCC_CR_HSIRDY));

    // Select HSI as the system clock source
    RCC->CFGR &= ~RCC_CFGR_SW;
    RCC->CFGR |= RCC_CFGR_SW_HSI;
    while ((RCC->CFGR & RCC_CFGR_SWS) != RCC_CFGR_SWS_HSI);

    // Update SystemCoreClock variable
    SystemCoreClockUpdate();
}

/**
 * @brief Configure Timer 11 for a 500 ms interrupt.
 */
void Timer11_Config(void) {
        // Enable the clock for Timer 11
    RCC->APB2ENR |= RCC_APB2ENR_TIM11EN;

    // Configure Timer 11 with a 1 ms tick and a 500 ms period
    Timer_Config(TIM11, 16000, 5000);

    // Enable the Timer 11 interrupt in the NVIC
    NVIC_EnableIRQ(TIM1_TRG_COM_TIM11_IRQn);
}

/**
 * @brief Generic timer configuration function.
 * @param TIMx Pointer to the TIM peripheral to configure (e.g., TIM11).
 * @param prescaler Prescaler value to divide the clock frequency.
 * @param period Auto-reload value to set the timer period.
 */
void Timer_Config(TIM_TypeDef *TIMx, uint32_t prescaler, uint32_t period) {
    // Set the prescaler (divides the clock frequency)
    TIMx->PSC = prescaler - 1;

    // Set the auto-reload register (determines the timer period)
    TIMx->ARR = period - 1;

    // Enable the update interrupt (UIE)
    TIMx->DIER |= TIM_DIER_UIE;

    // Enable the timer
    TIMx->CR1 |= TIM_CR1_CEN;
}

/**
 * @brief Timer 11 interrupt service routine.
 */
void TIM1_TRG_COM_TIM11_IRQHandler(void) {
    // Check if the update interrupt flag is set
    if (TIM11->SR & TIM_SR_UIF) {
        // Clear the interrupt flag
        TIM11->SR &= ~TIM_SR_UIF;

        // Toggle the LED on PC13
        GPIOC->ODR ^= GPIO_ODR_OD13;
    }
}
